version: '3.5'

services:
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
     - ./data/mysql:/var/lib/mysql:delegated
    restart: on-failure

  t3:
    image: vergissberlin/typo3
    links:
      - db
    depends_on:
      - db
    volumes:
      - ./data/web/typo3conf:/var/www/html/typo3conf:delegated
    restart: on-failure
